-- liquibase formatted sql

--changeset user:Library_2024_tables_001 dbms:oracle
CREATE TABLE AUTHORS
(	 AUTHOR_ID NUMBER,
     AUTHOR_NAME VARCHAR2(50 CHAR) NOT NULL ,
     NATIONALITY VARCHAR2(50 CHAR) NOT NULL ,
     PRIMARY KEY (AUTHOR_ID),
     CONSTRAINT AUTHORS_pk UNIQUE (AUTHOR_NAME)
);

--changeset user:Library_2024_tables_002 dbms:oracle
CREATE TABLE BOOKS
(	BOOK_ID NUMBER,
     TITLE VARCHAR2(50 CHAR) NOT NULL ,
     AUTHOR_ID NUMBER NOT NULL ,
     GENRE VARCHAR2(50 CHAR) NOT NULL ,
     PUBLICATION_YEAR NUMBER,
     PRIMARY KEY (BOOK_ID),
     FOREIGN KEY (AUTHOR_ID)
         REFERENCES AUTHORS (AUTHOR_ID) ON DELETE CASCADE
);

--changeset user:Library_2024_tables_003 dbms:oracle
CREATE TABLE STUDENTS
(	STUDENT_ID NUMBER,
     STUDENT_NAME VARCHAR2(50 CHAR) NOT NULL ,
     ROLE VARCHAR2(30 CHAR) NOT NULL ,
     PASSWORD VARCHAR2(60 CHAR) NOT NULL ,
     PRIMARY KEY (STUDENT_ID),
     CONSTRAINT STUDENTS_pk UNIQUE (STUDENT_NAME)
);

--changeset user:Library_2024_tables_004 dbms:oracle
CREATE TABLE REPORTS
(	RENTAL_ID NUMBER,
     BOOK_ID NUMBER NOT NULL ,
     STUDENT_ID NUMBER NOT NULL ,
     RENTAL_DATE TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ,
     RETURN_DATE TIMESTAMP (6),
     PRIMARY KEY (RENTAL_ID),
     CONSTRAINT REPORTS_pk UNIQUE (BOOK_ID, STUDENT_ID, RETURN_DATE),
     FOREIGN KEY (BOOK_ID)
         REFERENCES BOOKS (BOOK_ID) ON DELETE CASCADE ,
     FOREIGN KEY (STUDENT_ID)
         REFERENCES STUDENTS (STUDENT_ID) ON DELETE CASCADE
);

